# Generated by Django 5.0.3 on 2024-03-12 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundromat_app', '0003_rename_email_laundromat_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_ID', models.CharField(max_length=100, unique=True)),
                ('machine_choice', models.CharField(choices=[('Dryer', 'Dryer'), ('Washer', 'Washer')], max_length=6)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Resvered', 'Reserved')], default='Open', max_length=8)),
                ('laundromat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laundromat_app.laundromat')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reservations', to=settings.AUTH_USER_MODEL)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='laundromat_app.machines')),
            ],
            options={
                'ordering': ['date', 'start_time'],
                'unique_together': {('machine', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
