# Generated by Django 4.2.6 on 2024-03-07 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundromat_app', '0003_rename_email_laundromat_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundromat',
            name='hours',
            field=models.IntegerField(default=12),
            preserve_default=False,
        ),
    ]
