# Generated by Django 4.2.6 on 2024-03-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundromat_app', '0004_machines'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundromat',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laundromat',
            name='hours',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
