# Generated by Django 4.2.6 on 2024-03-07 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundromat_app', '0004_laundromat_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='laundromat',
            name='description',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
