# Generated by Django 4.2.5 on 2024-03-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laundromat_app', '0004_machines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Reserved', 'Reserved')], default='Open', max_length=8),
        ),
    ]
